EXERCISES = {
    "box-breathing": {
        "id": "box-breathing",
        "title": "Box Breathing",
        "subtitle": "Calm your nervous system",
        "icon": "🫁",
        "color": "#0891b2",
        "duration": "4 min",
        "target": ["anxiety", "stress", "panic"],
        "steps": [
            {"phase": "inhale",  "duration": 4, "instruction": "Breathe in slowly through your nose"},
            {"phase": "hold",    "duration": 4, "instruction": "Hold your breath gently"},
            {"phase": "exhale",  "duration": 4, "instruction": "Breathe out slowly through your mouth"},
            {"phase": "hold",    "duration": 4, "instruction": "Hold and rest before the next breath"},
        ],
        "rounds": 4,
        "intro": "Welcome to box breathing. This technique will calm your nervous system in just a few minutes. Find a comfortable position, relax your shoulders, and let's begin together.",
        "outro": "Beautiful work. Take a moment to notice how you feel. Your nervous system has shifted into a calmer state. You can return to this exercise anytime you need grounding.",
    },
    "body-scan": {
        "id": "body-scan",
        "title": "Body Scan",
        "subtitle": "Release tension & reconnect",
        "icon": "🧘",
        "color": "#7c3aed",
        "duration": "6 min",
        "target": ["tension", "dissociation", "stress"],
        "steps": [
            {"phase": "focus", "duration": 20, "instruction": "Bring awareness to the top of your head"},
            {"phase": "focus", "duration": 20, "instruction": "Soften your forehead, eyes, and jaw"},
            {"phase": "focus", "duration": 20, "instruction": "Let your shoulders drop and relax"},
            {"phase": "focus", "duration": 20, "instruction": "Notice your chest and the rhythm of your breath"},
            {"phase": "focus", "duration": 20, "instruction": "Scan down through your belly and lower back"},
            {"phase": "focus", "duration": 20, "instruction": "Feel the weight of your legs and feet on the ground"},
        ],
        "rounds": 1,
        "intro": "This body scan will help you reconnect with yourself and release any tension you've been holding. There is nothing to do but notice. Let's begin at the very top of your head.",
        "outro": "You've completed your body scan. Carry this awareness with you. Your body has been working hard for you — it deserves this kind of attention.",
    },
    "grounding": {
        "id": "grounding",
        "title": "5-4-3-2-1 Grounding",
        "subtitle": "Anchor to the present moment",
        "icon": "🌿",
        "color": "#059669",
        "duration": "3 min",
        "target": ["anxiety", "panic", "dissociation", "overwhelm"],
        "steps": [
            {"phase": "sense", "duration": 15, "instruction": "Name 5 things you can SEE around you right now"},
            {"phase": "sense", "duration": 15, "instruction": "Notice 4 things you can TOUCH or feel"},
            {"phase": "sense", "duration": 15, "instruction": "Identify 3 things you can HEAR"},
            {"phase": "sense", "duration": 15, "instruction": "Notice 2 things you can SMELL"},
            {"phase": "sense", "duration": 15, "instruction": "Find 1 thing you can TASTE"},
        ],
        "rounds": 1,
        "intro": "The 5-4-3-2-1 technique is one of the most powerful tools for anxiety and panic. It works by engaging your senses to pull your mind back to the present moment. Let's work through each sense together.",
        "outro": "You are here. You are present. You are safe. This technique is yours to use whenever anxiety pulls you away from the present moment.",
    },
    "progressive-relaxation": {
        "id": "progressive-relaxation",
        "title": "Progressive Relaxation",
        "subtitle": "Melt away muscle tension",
        "icon": "💆",
        "color": "#db2777",
        "duration": "8 min",
        "target": ["tension", "stress", "insomnia"],
        "steps": [
            {"phase": "tense",   "duration": 7,  "instruction": "Tense your hands into tight fists"},
            {"phase": "release", "duration": 10, "instruction": "Release and feel the warmth flood in"},
            {"phase": "tense",   "duration": 7,  "instruction": "Tense your arms and biceps"},
            {"phase": "release", "duration": 10, "instruction": "Let them go completely soft"},
            {"phase": "tense",   "duration": 7,  "instruction": "Scrunch your face and shoulders up"},
            {"phase": "release", "duration": 10, "instruction": "Release everything and breathe"},
            {"phase": "tense",   "duration": 7,  "instruction": "Tense your core and stomach"},
            {"phase": "release", "duration": 10, "instruction": "Soften completely and sink deeper"},
        ],
        "rounds": 1,
        "intro": "Progressive muscle relaxation teaches your body the difference between tension and ease. We'll move through each muscle group — tensing, then releasing. The release is where the magic happens.",
        "outro": "Your body knows how to release. Remember this feeling of letting go. Sleep, rest, and recovery come more easily when your body feels this safe.",
    },
    "gratitude": {
        "id": "gratitude",
        "title": "Gratitude Reflection",
        "subtitle": "Shift your emotional baseline",
        "icon": "🌸",
        "color": "#d97706",
        "duration": "4 min",
        "target": ["depression", "negativity", "sadness"],
        "steps": [
            {"phase": "reflect", "duration": 30, "instruction": "Think of one person who makes your life warmer"},
            {"phase": "reflect", "duration": 30, "instruction": "Recall a small moment today that felt okay"},
            {"phase": "reflect", "duration": 30, "instruction": "Name one thing your body did well today"},
            {"phase": "reflect", "duration": 30, "instruction": "Think of something simple you're glad exists"},
        ],
        "rounds": 1,
        "intro": "Gratitude isn't about ignoring pain — it's about widening your view. Research shows that even brief gratitude practice shifts our emotional baseline over time. Let's take a few minutes to look for the light.",
        "outro": "Well done. These small moments of noticing are quietly powerful. The more we practice looking for what's good, the more naturally it comes.",
    },
    "coherent-breathing": {
        "id": "coherent-breathing",
        "title": "Coherent Breathing",
        "subtitle": "Restore heart-brain harmony",
        "icon": "💛",
        "color": "#0d9488",
        "duration": "5 min",
        "target": ["anxiety", "depression", "stress"],
        "steps": [
            {"phase": "inhale", "duration": 5, "instruction": "Breathe in gently and steadily"},
            {"phase": "exhale", "duration": 5, "instruction": "Breathe out at the same slow pace"},
        ],
        "rounds": 15,
        "intro": "Coherent breathing at five seconds in, five seconds out synchronises your heart rate with your breath. This state — called heart coherence — is deeply restorative for both anxiety and low mood.",
        "outro": "You've just spent several minutes in heart coherence. This is a state your body loves. Even five minutes a day of this practice creates lasting changes in your nervous system.",
    },
}